name: CI-compile

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.2.0
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip gawk

    - name: git checkout
      uses: actions/checkout@v2
    - run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow

    - name: Compile -> make clean release
      run: |
        make --trace clean release LOCALVERSION=OSDLang

    - name: Create detailed changelog
      run: sh ./make_changelog.sh

    - name: Upload release artifact ELF
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: OPNPS2LD
        path: |
          OPNPS2LD-*.ELF

    - name: Upload release artifact info
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: INFO
        path: |
          DETAILED_CHANGELOG
          CREDITS
          LICENSE
          README.md


  build-debug:
    strategy:
      fail-fast: false
      matrix:
        debug: [debug, iopcore_debug, ingame_debug, deci2_debug] # eesio_debug broken
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: apk add build-base git zip gawk python3 py3-pip bash

    - name: git checkout
      uses: actions/checkout@v3

    - run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow
    - name: Install Python packages
      run: pip3 install -r requirements.txt

    - name: Get version
      id: version
      run: echo "::set-output name=version::$(make oplversion)"

    - name: Compile -> make debug
      run: |
        make ${{ matrix.debug }} --trace
        mv opl.elf opl-${{ matrix.debug }}.elf
    - name: Upload variants artifact ELF
      uses: actions/upload-artifact@v3
      with:
        name: opl-debug-${{ steps.version.outputs.version }}-${{ matrix.docker }}
        path: opl-*.elf


  release:
    needs: [build, build-debug]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
    steps:
    - name: git checkout
      uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Get version
      id: version
      run: echo "::set-output name=version::$(make oplversion)"

    - name: Download release artifact
      uses: actions/download-artifact@v1
      with:
        name: OPNPS2LD

    - name: Download variants artifact
      uses: actions/download-artifact@v1
      with:
        name: OPNPS2LD-VARIANTS

    - name: Download info artifact
      uses: actions/download-artifact@v1
      with:
        name: INFO

    - name: Prepare artifacts for release
      run: |
        cp INFO/* OPNPS2LD/
        cp INFO/* OPNPS2LD-VARIANTS/
        7z a -t7z OPNPS2LD-${{ steps.version.outputs.version }}.7z OPNPS2LD/*
        7z a -t7z OPNPS2LD-VARIANTS-${{ steps.version.outputs.version }}.7z OPNPS2LD-VARIANTS/*

    - name: Create prerelease
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "latest"
        title: "${{ steps.version.outputs.version }}"
        files: |
          OPNPS2LD-${{ steps.version.outputs.version }}.7z
          OPNPS2LD-VARIANTS-${{ steps.version.outputs.version }}.7z

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: "${{ contains(github.ref, '-rc') }}"
        title: "${{ steps.version.outputs.version }}"
        files: |
          OPNPS2LD-${{ steps.version.outputs.version }}.7z
          OPNPS2LD-VARIANTS-${{ steps.version.outputs.version }}.7z
